use p08_carrental;
SET SQL_SAFE_UPDATES = 0;


DELETE FROM car_availability;
DELETE FROM payment;
DELETE FROM booking;
DELETE FROM car;
DELETE FROM car_model;
DELETE FROM car_rental_agency;
DELETE FROM customer;
DELETE FROM users;
DELETE FROM car_manufacturer;
DELETE FROM status;
DELETE FROM category;
DELETE FROM fuel;
DELETE FROM mode_of_payment;
DELETE FROM roles;
DELETE FROM city;
SET SQL_SAFE_UPDATES = 1;
ALTER TABLE roles AUTO_INCREMENT = 1;
ALTER TABLE mode_of_payment AUTO_INCREMENT = 1;
ALTER TABLE fuel AUTO_INCREMENT = 1;
ALTER TABLE city AUTO_INCREMENT = 1;
ALTER TABLE category AUTO_INCREMENT = 1;
ALTER TABLE status AUTO_INCREMENT = 1;
ALTER TABLE car_manufacturer AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE customer AUTO_INCREMENT = 1;
ALTER TABLE car_rental_agency AUTO_INCREMENT = 1;
ALTER TABLE car_model AUTO_INCREMENT = 1;
ALTER TABLE car AUTO_INCREMENT = 1;
ALTER TABLE booking AUTO_INCREMENT = 1;
ALTER TABLE payment AUTO_INCREMENT = 1;
ALTER TABLE car_availability AUTO_INCREMENT = 1;





